FROM node:22

WORKDIR /app

COPY package.json package-lock.json ./
RUN npm ci

COPY . .

EXPOSE 80
EXPOSE 443

# Variables d'environnement à activer pour le SSL
ENV SSL_ENABLED=true

CMD ["npm", "start"]